###Registro de usuario
POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
"name":"marcelo",
"email":"marcelo@gmail.com",
"password":"marcelo123",
"c_password":"marcelo123"
}

### autentificacion (login)
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
"email":"marcelo@gmail.com",
"password":"marcelo123"
}

###perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 8|teemhCGrCdgPi1Cpwcw5v22xBSjdIx5z5dWkqhuk0a166bc9

###Cerrar sesion
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 8|teemhCGrCdgPi1Cpwcw5v22xBSjdIx5z5dWkqhuk0a166bc9
