POST http://127.0.0.1:8000/api/reset-password
Accept: application/json
Content-Type: application/json

{
    "email":"marcelo@gmail.com"
}


###Camnbio de contraseña
POST http://127.0.0.1:8000/api/change-password
Accept: application/json
Content-Type: application/json

{
    "token":"0419b6b2acbac9e5ed39a452ef8495f317a33688eb0a902b8b0da0b688ce9080",
    "email":"marcelo@gmail.com",
    "password":"marcelo1234",
    "password_confirmation":"marcelo1234"
}
